In [37]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import pickle

In [38]:
train_files = os.listdir('train/train/')
train_files.sort()
train_files

['10003.csv',
 '10005.csv',
 '10006.csv',
 '10007.csv',
 '10012.csv',
 '10013.csv',
 '10014.csv',
 '10016.csv',
 '10017.csv',
 '10018.csv',
 '10019.csv',
 '10020.csv',
 '10021.csv',
 '10022.csv',
 '10024.csv',
 '10025.csv',
 '10026.csv',
 '10028.csv',
 '10029.csv',
 '10030.csv',
 '10031.csv',
 '10033.csv',
 '10036.csv',
 '10037.csv',
 '10038.csv',
 '10039.csv',
 '10042.csv',
 '10046.csv',
 '10047.csv',
 '10049.csv',
 '10050.csv',
 '10052.csv',
 '10053.csv',
 '10054.csv',
 '10055.csv',
 '10056.csv',
 '10058.csv',
 '10059.csv',
 '10062.csv',
 '10064.csv',
 '10065.csv',
 '10066.csv',
 '10067.csv',
 '10070.csv',
 '10071.csv',
 '10072.csv',
 '10074.csv',
 '10075.csv',
 '10076.csv',
 '10077.csv',
 '10078.csv',
 '10079.csv',
 '10081.csv',
 '10082.csv',
 '10085.csv',
 '10086.csv',
 '10087.csv',
 '10088.csv',
 '10090.csv',
 '10091.csv',
 '10092.csv',
 '10094.csv',
 '10096.csv',
 '10098.csv',
 '10100.csv',
 '10101.csv',
 '10103.csv',
 '10106.csv',
 '10108.csv',
 '10109.csv',
 '10110.csv',
 '1011

# Each axis will have 3 features: avg, std, var -> 9 features per file

## Let's create X_train

In [40]:
colnames = ['x', 'y', 'z']
N = 9000
features = 9
X_train = np.zeros((N, features))
labels = []

for i, file in enumerate(train_files[:N]):
    
    full_path = f'train/train/{file}'
    temp_df = pd.read_csv(full_path, names=colnames)
#     index = map_file_to_label(file)
#     labels.append(train_labels_map[index])
    
    x = temp_df['x'].to_numpy()
    y = temp_df['y'].to_numpy()
    z = temp_df['z'].to_numpy()
    
    mean_x, std_x, var_x = np.mean(x), np.std(x), np.var(x)
    mean_y, std_y, var_y = np.mean(y), np.std(y), np.var(y)
    mean_z, std_z, var_z = np.mean(z), np.std(z), np.var(z)
    row = [mean_x, std_x, var_x, mean_y, std_y, var_y, mean_z, std_z, var_z]
    
    X_train[i] = np.array(row)

File 10003.csv; len_x: 150, len_y: 150, len_z: 150
File 10005.csv; len_x: 149, len_y: 149, len_z: 149
File 10006.csv; len_x: 150, len_y: 150, len_z: 150
File 10007.csv; len_x: 150, len_y: 150, len_z: 150
File 10012.csv; len_x: 150, len_y: 150, len_z: 150
File 10013.csv; len_x: 149, len_y: 149, len_z: 149
File 10014.csv; len_x: 150, len_y: 150, len_z: 150
File 10016.csv; len_x: 151, len_y: 151, len_z: 151
File 10017.csv; len_x: 150, len_y: 150, len_z: 150
File 10018.csv; len_x: 150, len_y: 150, len_z: 150
File 10019.csv; len_x: 149, len_y: 149, len_z: 149
File 10020.csv; len_x: 149, len_y: 149, len_z: 149
File 10021.csv; len_x: 150, len_y: 150, len_z: 150
File 10022.csv; len_x: 150, len_y: 150, len_z: 150
File 10024.csv; len_x: 150, len_y: 150, len_z: 150
File 10025.csv; len_x: 150, len_y: 150, len_z: 150
File 10026.csv; len_x: 149, len_y: 149, len_z: 149
File 10028.csv; len_x: 150, len_y: 150, len_z: 150
File 10029.csv; len_x: 150, len_y: 150, len_z: 150
File 10030.csv; len_x: 150, len

In [42]:
X_train

array([[ 1.59010940e-01,  5.44393051e-01,  2.96363794e-01, ...,
         8.13342643e+00,  4.42429811e-01,  1.95744138e-01],
       [ 1.74547752e-01,  6.17015065e-01,  3.80707590e-01, ...,
         8.72946826e+00,  3.86236664e-01,  1.49178761e-01],
       [-1.61696002e+00,  8.51122136e-01,  7.24408891e-01, ...,
         8.03634944e+00,  4.18813963e-01,  1.75405135e-01],
       ...,
       [-4.06112460e-01,  6.55641942e-01,  4.29866356e-01, ...,
         8.77203979e+00,  5.35075014e-01,  2.86305270e-01],
       [ 8.15228667e-03,  6.80594980e-01,  4.63209527e-01, ...,
         8.48209796e+00,  8.69155016e-01,  7.55430442e-01],
       [-5.17633651e-01,  5.38173469e-01,  2.89630682e-01, ...,
         7.45196084e+00,  3.49370740e-01,  1.22059914e-01]])

In [43]:
# Save X_train
with open('X_train_9.npy', 'wb') as f:
    np.save(f, X_train)

In [44]:
## y_train is the same everywhere

## Let's Create X_test

In [47]:
test_files = os.listdir('test/test/')
test_files.sort()
print(test_files[:5], len(test_files))

['10001.csv', '10002.csv', '10004.csv', '10008.csv', '10009.csv'] 5000


In [48]:
colnames = ['x', 'y', 'z']
N = 5000
features = 9
# X_test = np.zeros((N, features))
X_test = np.zeros((N, features))

for i, file in enumerate(test_files[:N]):
    print(f'File {file}')
    file_path = f'test/test/{file}'
    temp_df = pd.read_csv(f'test/test/{file}', names=colnames)
    x = temp_df['x'].to_numpy()
    y = temp_df['y'].to_numpy()
    z = temp_df['z'].to_numpy()
    
    mean_x, std_x, var_x = np.mean(x), np.std(x), np.var(x)
    mean_y, std_y, var_y = np.mean(y), np.std(y), np.var(y)
    mean_z, std_z, var_z = np.mean(z), np.std(z), np.var(z)
          
    row = [mean_x, std_x, var_x, mean_y, std_y, var_y, mean_z, std_z, var_z]

#     X_test[i] = np.array(row)
    X_test[i] = np.array(row)

File 10001.csv
File 10002.csv
File 10004.csv
File 10008.csv
File 10009.csv
File 10010.csv
File 10011.csv
File 10015.csv
File 10023.csv
File 10027.csv
File 10032.csv
File 10034.csv
File 10035.csv
File 10040.csv
File 10041.csv
File 10043.csv
File 10044.csv
File 10045.csv
File 10048.csv
File 10051.csv
File 10057.csv
File 10060.csv
File 10061.csv
File 10063.csv
File 10068.csv
File 10069.csv
File 10073.csv
File 10080.csv
File 10083.csv
File 10084.csv
File 10089.csv
File 10093.csv
File 10095.csv
File 10097.csv
File 10099.csv
File 10102.csv
File 10104.csv
File 10105.csv
File 10107.csv
File 10115.csv
File 10116.csv
File 10118.csv
File 10123.csv
File 10126.csv
File 10127.csv
File 10129.csv
File 10130.csv
File 10131.csv
File 10134.csv
File 10136.csv
File 10137.csv
File 10139.csv
File 10141.csv
File 10147.csv
File 10148.csv
File 10149.csv
File 10151.csv
File 10152.csv
File 10156.csv
File 10157.csv
File 10158.csv
File 10160.csv
File 10162.csv
File 10167.csv
File 10171.csv
File 10175.csv
File 10177

In [51]:
X_test.shape

(5000, 9)

In [52]:
X_test

array([[-3.05412347e-01,  7.42857043e-01,  5.51836586e-01, ...,
         8.57556766e+00,  9.65011797e-01,  9.31247768e-01],
       [-3.54157081e-01,  7.94335631e-01,  6.30969095e-01, ...,
         7.68358773e+00,  4.39248036e-01,  1.92938837e-01],
       [-8.47212227e-01,  3.84535013e-01,  1.47867176e-01, ...,
         8.73888807e+00,  3.90374426e-01,  1.52392192e-01],
       ...,
       [ 4.29758667e-03,  3.23994204e-01,  1.04972244e-01, ...,
         7.25703291e+00,  4.84647030e-01,  2.34882744e-01],
       [-1.05151830e+00,  5.01833910e-01,  2.51837273e-01, ...,
         8.55153351e+00,  4.80319851e-01,  2.30707159e-01],
       [-5.40031205e-01,  4.61364725e-01,  2.12857410e-01, ...,
         8.50877877e+00,  6.51297512e-01,  4.24188449e-01]])

In [53]:
# Save X_test
with open('X_test_9.npy', 'wb') as f:
    np.save(f, X_test)

# Each axis will have 5 features: avg, std, var, min, max -> 15 features per file

## X_train

In [54]:
colnames = ['x', 'y', 'z']
N = 9000
features = 15
X_train = np.zeros((N, features))
labels = []

for i, file in enumerate(train_files[:N]):
    
    full_path = f'train/train/{file}'
    temp_df = pd.read_csv(full_path, names=colnames)
#     index = map_file_to_label(file)
#     labels.append(train_labels_map[index])
    
    x = temp_df['x'].to_numpy()
    y = temp_df['y'].to_numpy()
    z = temp_df['z'].to_numpy()
    
    mean_x, std_x, var_x, min_x, max_x = np.mean(x), np.std(x), np.var(x), np.min(x), np.max(x)
    mean_y, std_y, var_y, min_y, max_y = np.mean(y), np.std(y), np.var(y), np.min(y), np.max(y)
    mean_z, std_z, var_z, min_z, max_z = np.mean(z), np.std(z), np.var(z), np.min(z), np.max(z)
    row = [mean_x, std_x, var_x, min_x, max_x, mean_y, std_y, var_y,  min_y, max_y, mean_z, std_z, var_z, min_z, max_z]
    
    X_train[i] = np.array(row)

In [57]:
print(X_train.shape)
X_train

(9000, 15)


array([[ 1.59010940e-01,  5.44393051e-01,  2.96363794e-01, ...,
         1.95744138e-01,  6.51402400e+00,  9.69951000e+00],
       [ 1.74547752e-01,  6.17015065e-01,  3.80707590e-01, ...,
         1.49178761e-01,  7.63271500e+00,  9.89703100e+00],
       [-1.61696002e+00,  8.51122136e-01,  7.24408891e-01, ...,
         1.75405135e-01,  7.25143900e+00,  9.76475100e+00],
       ...,
       [-4.06112460e-01,  6.55641942e-01,  4.29866356e-01, ...,
         2.86305270e-01,  7.59620300e+00,  1.02860890e+01],
       [ 8.15228667e-03,  6.80594980e-01,  4.63209527e-01, ...,
         7.55430442e-01,  6.50085600e+00,  1.11833160e+01],
       [-5.17633651e-01,  5.38173469e-01,  2.89630682e-01, ...,
         1.22059914e-01,  6.73848100e+00,  8.35995400e+00]])

In [58]:
# Save X_train
with open('X_train_15.npy', 'wb') as f:
    np.save(f, X_train)

## X_test

In [69]:
test_files = os.listdir('test/test/')
test_files.sort()
print(test_files[:5], len(test_files))

['10001.csv', '10002.csv', '10004.csv', '10008.csv', '10009.csv'] 5000


In [70]:
colnames = ['x', 'y', 'z']
N = 5000
features = 15
X_test = np.zeros((N, features))

for i, file in enumerate(test_files[:N]):
    
    full_path = f'test/test/{file}'
    temp_df = pd.read_csv(full_path, names=colnames)
    
    x = temp_df['x'].to_numpy()
    y = temp_df['y'].to_numpy()
    z = temp_df['z'].to_numpy()
    
    mean_x, std_x, var_x, min_x, max_x = np.mean(x), np.std(x), np.var(x), np.min(x), np.max(x)
    mean_y, std_y, var_y, min_y, max_y = np.mean(y), np.std(y), np.var(y), np.min(y), np.max(y)
    mean_z, std_z, var_z, min_z, max_z = np.mean(z), np.std(z), np.var(z), np.min(z), np.max(z)
    row = [mean_x, std_x, var_x, min_x, max_x, mean_y, std_y, var_y,  min_y, max_y, mean_z, std_z, var_z, min_z, max_z]
    
    X_test[i] = np.array(row)

In [71]:
print(X_test.shape)
X_test

(5000, 15)


array([[-3.05412347e-01,  7.42857043e-01,  5.51836586e-01, ...,
         9.31247768e-01,  5.64133800e+00,  1.09385090e+01],
       [-3.54157081e-01,  7.94335631e-01,  6.30969095e-01, ...,
         1.92938837e-01,  6.62535500e+00,  8.55747500e+00],
       [-8.47212227e-01,  3.84535013e-01,  1.47867176e-01, ...,
         1.52392192e-01,  7.74883400e+00,  9.79108800e+00],
       ...,
       [ 4.29758667e-03,  3.23994204e-01,  1.04972244e-01, ...,
         2.34882744e-01,  6.26023900e+00,  8.59518400e+00],
       [-1.05151830e+00,  5.01833910e-01,  2.51837273e-01, ...,
         2.30707159e-01,  7.61296300e+00,  9.55705400e+00],
       [-5.40031205e-01,  4.61364725e-01,  2.12857410e-01, ...,
         4.24188449e-01,  5.58268000e+00,  1.06530010e+01]])

In [72]:
# Save X_test
with open('X_test_15.npy', 'wb') as f:
    np.save(f, X_test)