In [9]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 1.3/1.3 MB 7.1 MB/s eta 0:00:00


In [3]:
import numpy as np
import pickle
from sklearn.preprocessing import normalize

# 3 features per axis

## X_Train

In [16]:
# Load X_train
with open('3_features_per_axis/X_train_9.npy', 'rb') as f:
    X_train = np.load(f)
print(X_train.shape)
X_train

(9000, 9)


array([[ 1.59010940e-01,  5.44393051e-01,  2.96363794e-01, ...,
         8.13342643e+00,  4.42429811e-01,  1.95744138e-01],
       [ 1.74547752e-01,  6.17015065e-01,  3.80707590e-01, ...,
         8.72946826e+00,  3.86236664e-01,  1.49178761e-01],
       [-1.61696002e+00,  8.51122136e-01,  7.24408891e-01, ...,
         8.03634944e+00,  4.18813963e-01,  1.75405135e-01],
       ...,
       [-4.06112460e-01,  6.55641942e-01,  4.29866356e-01, ...,
         8.77203979e+00,  5.35075014e-01,  2.86305270e-01],
       [ 8.15228667e-03,  6.80594980e-01,  4.63209527e-01, ...,
         8.48209796e+00,  8.69155016e-01,  7.55430442e-01],
       [-5.17633651e-01,  5.38173469e-01,  2.89630682e-01, ...,
         7.45196084e+00,  3.49370740e-01,  1.22059914e-01]])

In [17]:
X_train_normalized, norms = normalize(X_train, axis=0, norm='max', return_norm=True)

In [18]:
X_train_normalized

array([[ 0.0499259 ,  0.23764323,  0.05647431, ...,  0.83017519,
         0.21968259,  0.04826044],
       [ 0.05480412,  0.26934483,  0.07254664, ...,  0.89101292,
         0.19178064,  0.03677981],
       [-0.50768953,  0.37153931,  0.13804146, ...,  0.82026659,
         0.20795646,  0.04324589],
       ...,
       [-0.12751029,  0.28620658,  0.0819142 , ...,  0.89535817,
         0.26568432,  0.07058816],
       [ 0.00255964,  0.2970993 ,  0.08826799, ...,  0.86576394,
         0.43156727,  0.1862503 ],
       [-0.16252547,  0.23492821,  0.05519126, ...,  0.76061831,
         0.17347536,  0.0300937 ]])

In [19]:
norms

array([3.18493867, 2.2907997 , 5.24776329, 8.18558804, 2.26152724,
       5.11450545, 9.79724098, 2.01395028, 4.05599574])

In [15]:
# Save X_train
with open('3_features_per_axis/X_train_9_ns.npy', 'wb') as f:
    np.save(f, X_train_normalized)

## X_test

In [20]:
# Load X_test
with open('3_features_per_axis/X_test_9.npy', 'rb') as f:
    X_test = np.load(f)
print(X_test.shape)
X_test

(5000, 9)


array([[-3.05412347e-01,  7.42857043e-01,  5.51836586e-01, ...,
         8.57556766e+00,  9.65011797e-01,  9.31247768e-01],
       [-3.54157081e-01,  7.94335631e-01,  6.30969095e-01, ...,
         7.68358773e+00,  4.39248036e-01,  1.92938837e-01],
       [-8.47212227e-01,  3.84535013e-01,  1.47867176e-01, ...,
         8.73888807e+00,  3.90374426e-01,  1.52392192e-01],
       ...,
       [ 4.29758667e-03,  3.23994204e-01,  1.04972244e-01, ...,
         7.25703291e+00,  4.84647030e-01,  2.34882744e-01],
       [-1.05151830e+00,  5.01833910e-01,  2.51837273e-01, ...,
         8.55153351e+00,  4.80319851e-01,  2.30707159e-01],
       [-5.40031205e-01,  4.61364725e-01,  2.12857410e-01, ...,
         8.50877877e+00,  6.51297512e-01,  4.24188449e-01]])

In [21]:
X_test_normalized, norms = normalize(X_test, axis=0, norm='max', return_norm=True)

In [22]:
X_test_normalized

array([[-0.09310528,  0.33921207,  0.11506483, ...,  0.87121729,
         0.36800667,  0.13542891],
       [-0.10796517,  0.36271882,  0.13156494, ...,  0.78059841,
         0.16750698,  0.02805859],
       [-0.25827356,  0.17559087,  0.03083215, ...,  0.88780949,
         0.14886905,  0.022162  ],
       ...,
       [ 0.00131012,  0.14794602,  0.02188802, ...,  0.73726344,
         0.18481986,  0.03415838],
       [-0.32055649,  0.22915327,  0.05251122, ...,  0.86877559,
         0.18316969,  0.03355114],
       [-0.1646291 ,  0.21067375,  0.04438343, ...,  0.86443201,
         0.24837192,  0.06168861]])

In [23]:
# Save X_train
with open('3_features_per_axis/X_test_9_ns.npy', 'wb') as f:
    np.save(f, X_test_normalized)

# 5 features per axis